# Generated by Django 3.2.6 on 2021-09-05 05:50

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('auctions', '0008_auto_20210905_1045'),
    ]

    operations = [
        migrations.RemoveConstraint(
            model_name='bid',
            name='value_gte_starting_bid',
        ),
        migrations.RemoveField(
            model_name='bid',
            name='starting_bid',
        ),
    ]
