# Generated by Django 3.2.6 on 2021-09-05 05:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('auctions', '0009_auto_20210905_1050'),
    ]

    operations = [
        migrations.AddField(
            model_name='listing',
            name='highest_bid',
            field=models.IntegerField(default=0),
            preserve_default=False,
        ),
    ]
